spring:
  application:
    name: bookmymovie-payment
    version: 1.0.0-SNAPSHOT
  profiles:
    active: logs-stdout, local
    group:
      my-local: local
  lifecycle:
    timeout-per-shutdown-phase: 1m
  cloud:
    gcp:
      core:
        enabled: true
      datastore:
        enabled: true
        namespace: bookmymovie
        project-id: bookmymovie-db
        emulator:
          enabled: true
          namespace: bookmymovie
          project-id: bookmymovie-db
          port: 9086
          data-dir: F:\Program-Files\Firestore-Emulator-Data-Dir
      active: logs-stdout-json-gke
      grourp:
        my-local: local

server:
  port: 8086
  shutdown: graceful

logging:
  level:
    root: INFO

management:
  server:
    port: 7085
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      stackdriver:
        enabled: true
      prometheus:
        enabled: false

aspect:
  enabled: true

order:
  service:
    async:
      url: http://localhost:8085/order/order-async

acknowledgement:
  code: ACK

success:
  code: 255
  msg: 'Successful!'

error.code.map: {\
exception:'455',\
coversionException:'456',\
recordNotFoundException:'457',\
datastoreException:'458',\
transactionNotFoundException:'459',\
paymentProcessException:'460'\
}

error.msg.map: {\
exception:'Failed!',\
coversionException:'Conversion Error!',\
recordNotFoundException:'Invalid Record!',\
datastoreException:'DB Error!',\
transactionNotFoundException:'Transaction Not Found!',\
paymentProcessException:'460'\
}

bmm:
  metrics:
    tag:
      env: LOCAL