apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: poc-sell-orchestrator-gateway
  namespace: poc-sell-orchestrator-namespace
spec:
  selector:
    istio: ingressgateway #Istio default gateway implementation
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"