spring:
  application:
    name: bookmymovie-orchestrator
    version: 1.0.0-SNAPSHOT
  profiles:
    active: logs-stdout, local
    group:
      my-local: local
  lifecycle:
    timeout-per-shutdown-phase: 1m
  cloud:
    gcp:
      core:
        enabled: true
      datastore:
        enabled: true
        namespace: bookmymovie
        project-id: bookmymovie-db
        emulator:
          enabled: true
          namespace: bookmymovie
          project-id: bookmymovie-db
          port: 9081
          data-dir: F:\Program-Files\Firestore-Emulator-Data-Dir
      active: logs-stdout-json-gke
      grourp:
        my-local: local

server:
  port: 8081
  shutdown: graceful

logging:
  level:
    root: INFO

seat:
  book:
    limit: 10
