spring:
  application:
    name: bookmymovie-orchestrator
    version: 1.0.0-SNAPSHOT
  profiles:
    active: logs-stdout, local
    group:
      my-local: local
  lifecycle:
    timeout-per-shutdown-phase: 1m
  cloud:
    gcp:
      core:
        enabled: true
      datastore:
        enabled: true
        namespace: bookmymovie
        project-id: bookmymovie-db
        emulator:
          enabled: true
          namespace: bookmymovie
          project-id: bookmymovie-db
          port: 9081
          data-dir: F:\Program-Files\Firestore-Emulator-Data-Dir
      active: logs-stdout-json-gke
      grourp:
        my-local: local

server:
  port: 8081
  shutdown: graceful

logging:
  level:
    root: INFO

management:
  server:
    port: 7081
  endpoints:
    metrics:
      enabled: true
    web:
      exposure:
        include: health,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      stackdriver:
        enabled: true
      prometheus:
        enabled: false

aspect:
  enabled: true

seat:
  book:
    limit: 10

order:
  service:
    url: http://localhost:8085/order/order-new

acknowledgement:
  code: ACK

success:
  code: 255
  msg: 'Successful!'

error.code.map: {\
exception:'455',\
coversionException:'456',\
recordNotFoundException:'457',\
datastoreException:'458',\
bookingException:'462'\
}

error.msg.map: {\
exception:'Failed!',\
coversionException:'Conversion Error!',\
recordNotFoundException:'Invalid Record!',\
datastoreException:'DB Error!',\
bookingException:'Booking Failed!'\
}

bmm:
  metrics:
    tag:
      env: LOCAL