# security:
#   user:
#     name: user
#     password: password

# All files in this directory should be encrypted using vault password from corresponding cluster and namespace.
# Only encrypted files containing sensitive data should be committed to the repository.
# During deployment all files from this directory will be decrypted and stored in ./decode/ directory to use in helm/templates/secrets.yaml
#
# Encrypt the file:
#
# ansible-vault encrypt application-gke-secrets.properties

# Decrypt the file:
#
# ansible-vault decrypt application-gke-secrets.properties

# Documentation on vault.yaml http://ngp.sabre.com/tech-docs/NGP-CICD/chunks/vault_concept/vault_concept.html
